=== ep-infosec/50_google_skia-buildbot/perf/go/config/instanceConfigSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/InstanceConfig",
  "definitions": {
    "AuthConfig": {
      "required": [
        "header_name",
        "login_url",
        "logout_url"
      ],
      "properties": {
        "header_name": {
          "type": "string"
        },
        "email_regex": {
          "type": "string"
        },
        "login_url": {
          "type": "string"
        },
        "logout_url": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "CacheConfig": {
      "required": [
        "memcached_servers",
        "namespace"
      ],
      "properties": {
        "memcached_servers": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "namespace": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "DataStoreConfig": {
      "required": [
        "datastore_type",
        "connection_string",
        "tile_size"
      ],
      "properties": {
        "datastore_type": {
          "type": "string"
        },
        "connection_string": {
          "type": "string"
        },
        "tile_size": {
          "type": "integer"
        },
        "cache": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/CacheConfig"
        },
        "enable_follower_reads": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "GitRepoConfig": {
      "required": [
        "url",
        "dir"
      ],
      "properties": {
        "git_auth_type": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "dir": {
          "type": "string"
        },
        "file_change_marker": {
          "type": "string"
        },
        "debounce_commit_url": {
          "type": "boolean"
        },
        "commit_url": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "IngestionConfig": {
      "required": [
        "source_config",
        "branches",
        "file_ingestion_pubsub_topic_name"
      ],
      "properties": {
        "source_config": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/SourceConfig"
        },
        "branches": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "file_ingestion_pubsub_topic_name": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "InstanceConfig": {
      "required": [
        "URL",
        "contact",
        "data_store_config",
        "ingestion_config",
        "git_repo_config"
      ],
      "properties": {
        "URL": {
          "type": "string"
        },
        "contact": {
          "type": "string"
        },
        "auth_config": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/AuthConfig"
        },
        "data_store_config": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/DataStoreConfig"
        },
        "ingestion_config": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/IngestionConfig"
        },
        "git_repo_config": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/GitRepoConfig"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "SourceConfig": {
      "required": [
        "source_type",
        "project",
        "topic",
        "subscription",
        "sources"
      ],
      "properties": {
        "source_type": {
          "type": "string"
        },
        "project": {
          "type": "string"
        },
        "topic": {
          "type": "string"
        },
        "subscription": {
          "type": "string"
        },
        "sources": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "reject_if_name_matches": {
          "type": "string"
        },
        "accept_if_name_matches": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
  }
}

=== ep-infosec/50_google_skia-buildbot/perf/configs/flutter-engine2.json
{
    "URL": "https://flutter-engine-perf.skia.org/",
    "contact": "https://mail.google.com/chat/u/0/?zx=s88snihcl7ie#chat/space/AAAAm69vf-M",
    "auth_config": {
        "header_name": "X-WEBAUTH-USER",
        "login_url": "https://skia.org/login/",
        "logout_url": "https://skia.org/logout/"
    },
    "data_store_config": {
        "datastore_type": "cockroachdb",
        "connection_string": "postgresql://root@perf-cockroachdb-public:26257/flutter_engine2?sslmode=disable",
        "tile_size": 4096
    },
    "ingestion_config": {
        "source_config": {
            "source_type": "gcs",
            "project": "skia-public",
            "topic": "perf-ingestion-flutter-engine2",
            "subscription": "perf-ingestion-flutter-engine2-cdb-prod",
            "sources": [
                "gs://flutter-skia-perf-prod/flutter-engine"
            ],
            "reject_if_name_matches": ".lock$"
        },
        "branches": [],
        "file_ingestion_pubsub_topic_name": ""
    },
    "git_repo_config": {
        "url": "https://github.com/flutter/engine",
        "dir": "/tmp/flutter-engine",
        "debounce_commit_url": false,
        "commit_url": "%s/commit/%s"
    }
}

=== ep-infosec/50_google_skia-buildbot/perf/configs/flutter-flutter2.json
{
    "URL": "https://flutter-flutter-perf.skia.org/",
    "contact": "https://mail.google.com/chat/u/0/?zx=s88snihcl7ie#chat/space/AAAAm69vf-M",
    "auth_config": {
        "header_name": "X-WEBAUTH-USER",
        "login_url": "https://skia.org/login/",
        "logout_url": "https://skia.org/logout/"
    },
    "data_store_config": {
        "datastore_type": "cockroachdb",
        "connection_string": "postgresql://root@perf-cockroachdb-public:26257/flutter_flutter2?sslmode=disable",
        "tile_size": 4096
    },
    "ingestion_config": {
        "source_config": {
            "source_type": "gcs",
            "project": "skia-public",
            "topic": "perf-ingestion-flutter-flutter2",
            "subscription": "perf-ingestion-flutter-flutter2-cdb-prod",
            "sources": [
                "gs://flutter-skia-perf-prod/flutter-flutter"
            ],
            "reject_if_name_matches": ".lock$"
        },
        "branches": [],
        "file_ingestion_pubsub_topic_name": ""
    },
    "git_repo_config": {
        "url": "https://github.com/flutter/flutter",
        "dir": "/tmp/flutter-flutter",
        "debounce_commit_url": false,
        "commit_url": "%s/commit/%s"
    }
}

=== ep-infosec/50_google_skia-buildbot/perf/configs/angle.json
{
  "URL": "https://angle-perf.skia.org",
  "contact": "https://bugs.chromium.org/p/angle/issues/list?q=component%3ATools&can=2",
  "auth_config": {
    "header_name": "X-WEBAUTH-USER",
    "login_url": "https://skia.org/login/",
    "logout_url": "https://skia.org/logout/"
  },
  "data_store_config": {
    "datastore_type": "cockroachdb",
    "connection_string": "postgresql://root@perf-cockroachdb-public:26257/angle?sslmode=disable",
    "tile_size": 256
  },
  "ingestion_config": {
    "source_config": {
      "source_type": "gcs",
      "project": "skia-public",
      "topic": "perf-ingestion-angle",
      "subscription": "perf-ingestion-angle-prod",
      "sources": [
        "gs://angle-perf-skia/angle_perftests"
      ]
    },
    "branches": [],
    "file_ingestion_pubsub_topic_name": ""
  },
  "git_repo_config": {
    "url": "https://chromium.googlesource.com/angle/angle",
    "dir": "/tmp/angle",
    "debounce_commit_url": false
  }
}

=== ep-infosec/50_google_skia-buildbot/perf/configs/comp-ui.json
{
    "URL": "https://comp-ui-perf.skia.org",
    "contact": "https://bugs.skia.org",
    "auth_config": {
        "header_name": "X-WEBAUTH-USER",
        "login_url": "https://skia.org/login/",
        "logout_url": "https://skia.org/logout/"
    },
    "data_store_config": {
        "datastore_type": "cockroachdb",
        "connection_string": "postgresql://root@perf-cockroachdb-public:26257/compui?sslmode=disable",
        "tile_size": 256,
        "enable_follower_reads": true
    },
    "ingestion_config": {
        "source_config": {
            "source_type": "gcs",
            "project": "skia-public",
            "topic": "perf-ingestion-compui",
            "subscription": "perf-ingestion-compui-prod",
            "sources": [
                "gs://chrome-comp-ui-perf-skia/ingest"
            ]
        },
        "branches": [],
        "file_ingestion_pubsub_topic_name": ""
    },
    "git_repo_config": {
        "git_auth_type": "gerrit",
        "url": "https://skia.googlesource.com/perf-compui",
        "dir": "/tmp/compui-perf",
        "debounce_commit_url": false,
        "file_change_marker": ""
    }
}

=== ep-infosec/50_google_skia-buildbot/perf/configs/cdb-nano.json
{
  "URL": "https://perf.skia.org",
  "contact": "https://bugs.skia.org",
  "auth_config": {
    "header_name": "X-WEBAUTH-USER",
    "login_url": "https://skia.org/login/",
    "logout_url": "https://skia.org/logout/"
  },
  "data_store_config": {
    "datastore_type": "cockroachdb",
    "connection_string": "postgresql://root@perf-cockroachdb-public:26257/skia?sslmode=disable",
    "tile_size": 256,
    "enable_follower_reads": true
  },
  "ingestion_config": {
    "source_config": {
      "source_type": "gcs",
      "project": "skia-public",
      "topic": "perf-ingestion-skia-production",
      "subscription": "perf-ingestion-skia-production-cdb-prod",
      "sources": [
        "gs://skia-perf/nano-json-v1",
        "gs://skia-perf/task-duration",
        "gs://skia-perf/buildstats-json-v1",
        "gs://skia-perf/gold-summary-v1"
      ]
    },
    "branches": [],
    "file_ingestion_pubsub_topic_name": ""
  },
  "git_repo_config": {
    "url": "https://skia.googlesource.com/skia",
    "dir": "/tmp/skiaperf",
    "debounce_commit_url": false,
    "file_change_marker": "infra/bots/assets/skp/VERSION"
  }
}

=== ep-infosec/50_google_skia-buildbot/perf/configs/cdb-ct-prod.json
{
  "URL": "https://ct-perf.skia.org",
  "contact": "https://bugs.skia.org",
  "auth_config": {
    "header_name": "X-WEBAUTH-USER",
    "login_url": "https://skia.org/login/",
    "logout_url": "https://skia.org/logout/"
  },
  "data_store_config": {
    "datastore_type": "cockroachdb",
    "connection_string": "postgresql://root@perf-cockroachdb-public:26257/ct?sslmode=disable",
    "tile_size": 256
  },
  "ingestion_config": {
    "source_config": {
      "source_type": "gcs",
      "project": "skia-public",
      "topic": "perf-ingestion-ct-production",
      "subscription": "perf-ingestion-ct-cdb-prod",
      "sources": [
        "gs://cluster-telemetry-perf/ingest"
      ]
    },
    "branches": [],
    "file_ingestion_pubsub_topic_name": ""
  },
  "git_repo_config": {
    "url": "https://skia.googlesource.com/perf-ct",
    "dir": "/tmp/ct",
    "debounce_commit_url": false
  }
}

=== ep-infosec/50_google_skia-buildbot/perf/configs/demo.json
{
    "URL": "http://localhost:8001",
    "contact": "user@example.org",
    "data_store_config": {
        "datastore_type": "cockroachdb",
        "connection_string": "postgresql://root@localhost:26257/demo?sslmode=disable",
        "tile_size": 256
    },
    "ingestion_config": {
        "source_config": {
            "source_type": "dir",
            "sources": [
                "./demo/data/"
            ],
            "project": "",
            "topic": "",
            "subscription": ""
        },
        "branches": [],
        "file_ingestion_pubsub_topic_name": ""
    },
    "git_repo_config": {
        "url": "https://github.com/skia-dev/perf-demo-repo.git",
        "dir": "/tmp/perf-demo",
        "debounce_commit_url": false
    }
}

=== ep-infosec/50_google_skia-buildbot/perf/configs/v8.json
{
  "URL": "https://v8-perf.skia.org",
  "contact": "https://bugs.chromium.org/p/v8/issues/list?q=component%3ATools&can=2",
  "auth_config": {
    "header_name": "X-WEBAUTH-USER",
    "login_url": "https://skia.org/login/",
    "logout_url": "https://skia.org/logout/"
  },
  "data_store_config": {
    "datastore_type": "cockroachdb",
    "connection_string": "postgresql://root@perf-cockroachdb-public:26257/v8?sslmode=disable",
    "tile_size": 256
  },
  "ingestion_config": {
    "source_config": {
      "source_type": "gcs",
      "project": "skia-public",
      "topic": "perf-ingestion-v8-production",
      "subscription": "",
      "sources": [
        "gs://v8_perf_skia_prod/v8/cq/",
        "gs://v8_perf_skia_prod/v8/chromeperf/"
      ]
    },
    "branches": [],
    "file_ingestion_pubsub_topic_name": ""
  },
  "git_repo_config": {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "dir": "/tmp/v8",
    "debounce_commit_url": false
  }
}
