=== ep-infosec/50_google_skia-buildbot/perf/go/ingest/format/formatSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/Format",
  "definitions": {
    "Format": {
      "required": [
        "version",
        "git_hash",
        "results"
      ],
      "properties": {
        "version": {
          "type": "integer"
        },
        "git_hash": {
          "type": "string"
        },
        "issue": {
          "type": "string"
        },
        "patchset": {
          "type": "string"
        },
        "key": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "results": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/Result"
          },
          "type": "array"
        },
        "links": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "Result": {
      "required": [
        "key"
      ],
      "properties": {
        "key": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "measurement": {
          "type": "number"
        },
        "measurements": {
          "patternProperties": {
            ".*": {
              "items": {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "$ref": "#/definitions/SingleMeasurement"
              },
              "type": "array"
            }
          },
          "type": "object"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "SingleMeasurement": {
      "required": [
        "value",
        "measurement"
      ],
      "properties": {
        "value": {
          "type": "string"
        },
        "measurement": {
          "type": "number"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
  }
}

=== ep-infosec/50_google_skia-buildbot/perf/go/trybot/ingester/gerrit/testdata/success.json
{
  "version": 1,
  "git_hash": "fe4a4029a080bc955e9588d05a6cd9eb490845d4",
  "issue": "327697",
  "patchset": "1",
  "key": {
    "arch": "x86",
    "branch": "some-branch-name",
    "config": "meta",
    "gpu": "GTX660",
    "model": "ShuttleA",
    "os": "Ubuntu12",
    "system": "UNIX"
  },
  "results": [
    {
      "key": {
        "test": "memory_usage_0_0",
        "sub_result": "max_rss_mb"
      },
      "measurement": 858
    },
    {
      "key": {
        "test": "DeferredSurfaceCopy_discardable_640_480",
        "source_type": "bench",
        "sub_result": "min_ms"
      },
      "measurements": {
        "config": [
          {
            "value": "8888",
            "measurement": 2.223606
          },
          {
            "value": "565",
            "measurement": 2.215988
          },
          {
            "value": "gpu",
            "measurement": 0.115713274509804
          }
        ]
      }
    }
  ]
}

=== ep-infosec/50_google_skia-buildbot/perf/demo/data/demo_data_commit_3.json
{
  "version": 1,
  "git_hash": "6286eccdf042751401f54696ad38de9f6849284d",
  "key": {
    "arch": "x86",
    "config": "8888"
  },
  "results": [
    {
      "key": {
        "units": "ms"
      },
      "measurements": {
        "test": [
          {
            "value": "encode",
            "measurement": 51.27391
          },
          {
            "value": "decode",
            "measurement": 10.686823
          }
        ]
      }
    },
    {
      "key": {
        "units": "kb"
      },
      "measurements": {
        "test": [
          {
            "value": "encode",
            "measurement": 207
          },
          {
            "value": "decode",
            "measurement": 65
          }
        ]
      }
    }
  ]
}

=== ep-infosec/50_google_skia-buildbot/perf/go/ingest/parser/testdata/version_1/unknown_branch.json
{
  "version": 1,
  "git_hash": "fe4a4029a080bc955e9588d05a6cd9eb490845d4",
  "results": [
    {
      "key": {
        "test": "memory_usage_0_0",
        "sub_result": "max_rss_mb"
      },
      "measurements": {
        "sub_result": [
          {
            "value": "max_rss_mb",
            "measurement": 858
          }
        ]
      }
    }
  ],
  "key": {
    "branch": "ignoreme"
  }
}
